### ISSUE TITLE
Simpler comma separated list for test_dicts.py

### ISSUE THREAD

**Issue by simonsmithdatascience** [senntical/py_learning_game#2]
Here's my take on printing the races with comma separation:

races = ['elf', 'human', 'orc', 'tiefling', 'person who likes pineapple on pizza']
print(', '.join(races[:-1]) + ', or ' + races[-1])

**Comment by senntical** [comment]
Hmm, okay, I think I follow that. Lemme look up more about the [:-1] works (I've seen it before but forgot how it works) and then can go forward with seeing how to use it.

**Comment by senntical** [comment]
Ran a test of it and it ran nicely. I've replaced my old version with that one (well, left my old on in commented out cause notes and such, yay keeping notes on everything).
