### ISSUE TITLE
Use Python standard "if XYZ in List" syntax when checking if answer is valid answer

### ISSUE THREAD

**Issue by zachintosh** [senntical/py_learning_game#3]
Instead of using an if/elif for each possible answer to a question (like what race), you could check if the answer the player gives is in the List of valid answers with Python's "in" syntax.

https://appdividend.com/2020/01/21/python-list-contains-how-to-check-if-item-exists-in-list/#:~:text=To%20check%20if%20the%20item,not%2C%20then%20it%20returns%20false.

**Comment by senntical** [comment]
Used this idea to redo how the checking of player input compared against existing dictionary entries.
